import { relations } from "drizzle-orm";
import {
  bigint,
  date,
  index,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Better Auth owns the user/session/account tables; re-exported so Drizzle sees
// them as part of one schema. Generated by the Better Auth CLI — never hand-edited.
export * from "./auth-schema";

/**
 * Enum values are stable machine strings, not display text. Renaming what the UI
 * shows is then a change to the label maps below, never a database migration.
 */
export const agreementTypeEnum = pgEnum("agreement_type", [
  "nda",
  "msa",
  "sow",
  "dpa",
  "order_form",
  // Docusign holds plenty that fits none of the above. Without a home for those,
  // an imported record would have to be mislabelled as one of the named types.
  "other",
]);

export const agreementStatusEnum = pgEnum("agreement_status", [
  "draft",
  "in_review",
  "out_for_signature",
  "executed",
  "expired",
  // Docusign's declined/voided envelopes. Distinct from `expired`: an agreement
  // that expired was in force once, one that was voided never took effect.
  "voided",
]);

/**
 * Where a row came from.
 *
 * Docusign exposes the same agreement through two products, and which one a row
 * was built from decides whether the sync may overwrite it: `manual` rows are the
 * user's own and are never touched by an import.
 */
export const agreementSourceEnum = pgEnum("agreement_source", [
  "manual",
  "esignature",
  "agreement_manager",
]);

export type AgreementType = (typeof agreementTypeEnum.enumValues)[number];
export type AgreementStatus = (typeof agreementStatusEnum.enumValues)[number];
export type AgreementSource = (typeof agreementSourceEnum.enumValues)[number];

export const AGREEMENT_TYPE_LABELS: Record<AgreementType, string> = {
  nda: "NDA",
  msa: "MSA",
  sow: "SOW",
  dpa: "DPA",
  order_form: "Order Form",
  other: "Other",
};

export const AGREEMENT_STATUS_LABELS: Record<AgreementStatus, string> = {
  draft: "Draft",
  in_review: "In Review",
  out_for_signature: "Out for Signature",
  executed: "Executed",
  expired: "Expired",
  voided: "Voided",
};

export const AGREEMENT_SOURCE_LABELS: Record<AgreementSource, string> = {
  manual: "Added here",
  esignature: "eSignature",
  agreement_manager: "Agreement Manager",
};

/** A contract. Always belongs to exactly one user — every query filters on userId. */
export const agreement = pgTable(
  "agreement",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    counterparty: text("counterparty").notNull(),
    type: agreementTypeEnum("type").notNull().default("nda"),
    status: agreementStatusEnum("status").notNull().default("draft"),
    // Integer cents, so contract values never pick up floating-point rounding error.
    valueCents: bigint("value_cents", { mode: "number" }),
    currency: text("currency").notNull().default("USD"),
    owner: text("owner"),
    effectiveDate: date("effective_date"),
    expiryDate: date("expiry_date"),

    // --- Docusign provenance -------------------------------------------------
    // Null on rows created in this app; set on everything the sync imports.
    source: agreementSourceEnum("source").notNull().default("manual"),
    /** eSignature envelope id, when the row has (or came from) an envelope. */
    envelopeId: text("envelope_id"),
    /** Agreement Manager agreement id, when Agreement Manager knows this item. */
    agreementId: text("agreement_id"),
    /**
     * The identity the sync de-duplicates on: the envelope id when there is one,
     * otherwise the Agreement Manager id.
     *
     * Stored rather than derived because it is the upsert's conflict target — it
     * has to be a real column for Postgres to enforce uniqueness on it. Preferring
     * the envelope id is what makes an Agreement Manager record land on top of the
     * envelope row already showing in the table, instead of beside it.
     */
    externalKey: text("external_key"),
    lastSyncedAt: timestamp("last_synced_at"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("agreement_user_id_idx").on(table.userId),
    // Scoped to the user, so two people importing the same shared envelope each
    // keep their own row. Postgres counts NULLs as distinct, which is exactly
    // what manual rows need — they all have a null key and none of them collide.
    uniqueIndex("agreement_user_external_key_uq").on(table.userId, table.externalKey),
  ],
);

/** A chat thread. Scoped to its user like everything else. */
export const conversation = pgTable(
  "conversation",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull().default("New conversation"),
    // The Claude Agent SDK session this thread maps to. The SDK keeps the real
    // transcript — including tool calls and their results — so resuming by id gives
    // the agent context that a replay of the stored text alone would lose.
    //
    // Nullable and disposable: if the session can't be resumed the run starts fresh
    // rather than failing. The messages below, not this, are the durable record.
    agentSessionId: text("agent_session_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("conversation_user_id_idx").on(table.userId)],
);

export const messageRoleEnum = pgEnum("message_role", ["user", "assistant"]);

/**
 * One Docusign action the agent took while producing a message.
 *
 * Stored alongside the reply so "the agent sent an envelope" survives a refresh.
 * Without this the tool calls would exist only in the live stream, and reloading
 * the page would quietly erase the record of what was actually done.
 */
export type AgentToolCall = {
  /** The SDK's tool_use id — used to match a result back to its call. */
  id: string;
  /** Namespaced MCP tool name, e.g. `mcp__docusign__send_envelope`. */
  name: string;
  /** Arguments the agent passed. Kept so the UI can show what was acted on. */
  input: unknown;
  /** `running` only ever persists if a run was interrupted mid-tool. */
  status: "running" | "ok" | "error";
};

export const message = pgTable(
  "message",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    conversationId: uuid("conversation_id")
      .notNull()
      .references(() => conversation.id, { onDelete: "cascade" }),
    role: messageRoleEnum("role").notNull(),
    content: text("content").notNull(),
    // Null for user messages and for replies that needed no tools.
    toolCalls: jsonb("tool_calls").$type<AgentToolCall[]>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("message_conversation_id_idx").on(table.conversationId)],
);

/**
 * A user's linked Docusign account.
 *
 * Deliberately its own table rather than a row in Better Auth's `account`: Docusign
 * is not a way to sign in to this app, it is a resource a signed-in user connects.
 * Keeping them apart means Better Auth never treats these tokens as login
 * credentials, and unlinking Docusign can never orphan somebody's login.
 *
 * `userId` is unique — one Docusign connection per user, so reconnecting is an
 * upsert rather than a growing pile of stale tokens.
 */
export const docusignConnection = pgTable("docusign_connection", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .unique()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token").notNull(),
  refreshToken: text("refresh_token").notNull(),
  // Derived from the `expires_in` seconds Docusign returns, so the refresh path
  // can decide "is this stale?" without a probe request.
  accessTokenExpiresAt: timestamp("access_token_expires_at").notNull(),
  // What the user actually consented to, which can be narrower than what we asked
  // for. Recorded so a later scope change can tell it needs fresh consent.
  scope: text("scope").notNull(),
  // Which Docusign world these tokens belong to. A demo token is meaningless
  // against production, so the environment is pinned at connect time.
  environment: text("environment").notNull(),
  connectedAt: timestamp("connected_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const agreementRelations = relations(agreement, ({ one }) => ({
  user: one(user, { fields: [agreement.userId], references: [user.id] }),
}));

export const docusignConnectionRelations = relations(docusignConnection, ({ one }) => ({
  user: one(user, { fields: [docusignConnection.userId], references: [user.id] }),
}));

export const conversationRelations = relations(conversation, ({ one, many }) => ({
  user: one(user, { fields: [conversation.userId], references: [user.id] }),
  messages: many(message),
}));

export const messageRelations = relations(message, ({ one }) => ({
  conversation: one(conversation, {
    fields: [message.conversationId],
    references: [conversation.id],
  }),
}));

export type Agreement = typeof agreement.$inferSelect;
export type Conversation = typeof conversation.$inferSelect;
export type Message = typeof message.$inferSelect;
export type DocusignConnection = typeof docusignConnection.$inferSelect;
